basePath: /api/v1
definitions:
  admin.AuthForm:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  v1.AddArticleForm:
    properties:
      content:
        description: 内容
        type: string
      cover_image_url:
        description: 封面图片
        type: string
      created_by:
        description: 创建人
        type: string
      desc:
        description: 描述
        type: string
      state:
        description: 启用or 禁用
        type: integer
      tag_id:
        description: 分类id
        type: integer
      title:
        description: 标题
        type: string
    type: object
  v1.AddTagForm:
    properties:
      created_by:
        description: 创建人
        type: string
      name:
        description: 名称
        type: string
      state:
        description: 禁用 or 启用
        type: integer
    type: object
  v1.EditArticleForm:
    properties:
      content:
        description: 内容
        type: string
      cover_image_url:
        description: 封面图片
        type: string
      desc:
        description: 描述
        type: string
      id:
        description: id
        type: integer
      modified_by:
        description: 修改人
        type: string
      state:
        description: 启用or 禁用
        type: integer
      tag_id:
        description: 分类id
        type: integer
      title:
        description: 标题
        type: string
    type: object
  v1.EditTagForm:
    properties:
      id:
        description: id
        type: integer
      modified_by:
        description: 修改人
        type: string
      name:
        description: 名称
        type: string
      state:
        description: 禁用 or 启用
        type: integer
    type: object
info:
  contact: {}
  description: 博客系统的api接口文档
  license: {}
  title: 博客接口文档说明
  version: 1.0.0
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: 获取文章列表
      parameters:
      - description: 页数
        in: query
        name: page
        required: true
        type: integer
      - description: 标题
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 获取文章列表
    post:
      consumes:
      - application/json
      description: 新增文章
      parameters:
      - description: 新增文章
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/v1.AddArticleForm'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 新增文章
  /articles/{id}:
    delete:
      consumes:
      - application/json
      description: 删除文章
      parameters:
      - description: 唯一id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 删除文章
    get:
      consumes:
      - application/json
      description: 获取单个文章
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 获取单个文章
    put:
      consumes:
      - application/json
      description: 修改文章
      parameters:
      - description: 唯一id
        in: path
        name: id
        required: true
        type: integer
      - description: 新增文章
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/v1.EditArticleForm'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 修改文章
  /signin:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录参数
        in: body
        name: string
        required: true
        schema:
          $ref: '#/definitions/admin.AuthForm'
      produces:
      - application/json
      responses:
        "200": {}
        "500": {}
      summary: 登录
  /tags:
    get:
      consumes:
      - application/json
      description: 获取文章标签列表 带字段筛选 带分页
      parameters:
      - description: 当前页数
        in: query
        name: page
        required: true
        type: integer
      - description: 标签名称
        in: query
        name: name
        type: string
      - description: 标签名称
        in: query
        name: state
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 获取文章标签列表
    post:
      consumes:
      - application/json
      description: 新增文章标签
      parameters:
      - description: 新增文章标签
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/v1.AddTagForm'
      produces:
      - application/json
      responses:
        "200": {}
        "500": {}
      summary: 新增文章标签
  /tags/{id}:
    delete:
      consumes:
      - application/json
      description: 删除文章标签
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 删除文章标签
    put:
      consumes:
      - application/json
      description: 修改文章标签
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: 新增文章标签
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/v1.EditTagForm'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 修改文章标签
swagger: "2.0"
