basePath: /api/v1
definitions:
  admin.AuthBody:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  models.Tag:
    properties:
      created_by:
        description: 创建人
        type: string
      createdOn:
        description: 创建时间
        type: integer
      id:
        description: id标识
        type: integer
      modified_by:
        description: 修改人
        type: string
      modifiedOn:
        description: 修改时间
        type: integer
      name:
        description: 标签名称
        type: string
      state:
        description: 启用或禁用
        type: integer
    type: object
  v1.ArticleBody:
    properties:
      content:
        description: 内容
        type: string
      created_by:
        description: 创建人
        type: string
      desc:
        description: 描述信息
        type: string
      state:
        description: 禁用或启用
        type: integer
      tag_id:
        description: 标签id
        type: string
      title:
        description: 标题
        type: string
    type: object
info:
  contact: {}
  description: 博客系统的api接口文档
  license: {}
  title: 博客接口文档说明
  version: 1.0.0
paths:
  /articles:
    get:
      consumes:
      - application/json
      description: 获取文章列表
      parameters:
      - description: 页数
        in: query
        name: page
        required: true
        type: integer
      - description: 标题
        in: query
        name: title
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 获取文章列表
    post:
      consumes:
      - application/json
      description: 新增文章
      parameters:
      - description: 新增文章
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/v1.ArticleBody'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 新增文章
  /articles/{id}:
    delete:
      consumes:
      - application/json
      description: 删除文章
      parameters:
      - description: 唯一id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 删除文章
    get:
      consumes:
      - application/json
      description: 获取单个文章
      parameters:
      - description: id
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200": {}
      summary: 获取单个文章
    put:
      consumes:
      - application/json
      description: 修改文章
      parameters:
      - description: 唯一id
        in: path
        name: id
        required: true
        type: integer
      - description: 新增文章
        in: body
        name: state
        required: true
        schema:
          $ref: '#/definitions/v1.ArticleBody'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 修改文章
  /signin:
    post:
      consumes:
      - application/json
      description: 登录
      parameters:
      - description: 登录参数
        in: body
        name: username
        required: true
        schema:
          $ref: '#/definitions/admin.AuthBody'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 登录
  /tags:
    get:
      consumes:
      - application/json
      description: 获取文章标签列表 带字段筛选 带分页
      parameters:
      - description: 当前页数
        in: query
        name: page
        required: true
        type: integer
      - description: 标签名称
        in: query
        name: name
        type: string
      produces:
      - application/json
      responses:
        "200": {}
      summary: 获取文章标签列表
    post:
      consumes:
      - application/json
      description: 新增文章标签
      parameters:
      - description: 新增文章标签
        in: body
        name: created_by
        required: true
        schema:
          $ref: '#/definitions/models.Tag'
      produces:
      - application/json
      responses:
        "200": {}
      summary: 新增文章标签
swagger: "2.0"
